import Footer from '@/components/layout/Footer'
import Header from '@/components/layout/Header'
import type { Metadata } from 'next'
import getConfig from 'next/config'
import { Geist } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
  display: 'swap',
  subsets: ['latin'],
  variable: '--font-geist-sans',
})

const { publicRuntimeConfig } = getConfig()

export const metadata: Metadata = {
  title: publicRuntimeConfig.appName,
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode
  params: Promise<{ locale: string }>
}>) {
  const locale = (await params).locale

  return (
    <html lang={locale}>
      <body className={`${geistSans.variable} font-sans antialiased`}>
        <Header />

        {children}

        <Footer />
      </body>
    </html>
  )
}
