name: CI

on:
  push:
    branches: ["*"]
    tags: ["v*"]
  pull_request:
    branches: ["*"]

permissions:
  contents: write

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-

      - name: Install the latest version of Corepack
        run: npm i -g corepack@latest

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

  test:
    name: "Test"
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Create a .env.test file
        run: |
          touch .env.test
          echo "APP_NAME=\"Testing\"" >> .env.test
          echo "APP_HOST=\"${{ vars.APP_HOST }}\"" >> .env.test
          echo "CS_API_KEY=\"${{ vars.CS_API_KEY }}\"" >> .env.test
          echo "CS_DELIVERY_TOKEN=\"${{ vars.CS_DELIVERY_TOKEN }}\"" >> .env.test
          echo "CS_PREVIEW_TOKEN=\"${{ vars.CS_PREVIEW_TOKEN }}\"" >> .env.test
          echo "CS_API_ENDPOINT=\"${{ vars.CS_API_ENDPOINT }}\"" >> .env.test
          echo "CS_ENVIRONMENT=\"${{ vars.CS_ENVIRONMENT }}\"" >> .env.test
          echo "DISABLE_QUERY_CACHE=0" >> .env.test

      - name: Install the latest version of Corepack
        run: npm i -g corepack@latest

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm coverage

      - name: Delete the .env.test file after tests are completed
        run: rm .env.test

      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/

  sonar-scan:
    name: "SonarQube Scan"
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v4

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy:
    name: "Release"
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Release
        run: ls # Placeholder for now
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    if:
      startsWith(github.ref, 'refs/tags/')
